class ArchitecturesModel {
  final _architectures = {
    "layered": {
      "agility": 0,
      "abstraction": 0,
      "configurability": 0,
      "cost": 0,
      "deployability": 0,
      "domain": 0,
      "elasticity": 0,
      "evolvability": 0,
      "fault-tolerance": 0,
      "interoperability": 0,
      "performance": 0,
      "scalability": 0,
      "simplicity": 0,
      "testability": 0,
      "workflow": 0,
    },
    "modular monolith": {
      "agility": 0,
      "abstraction": 0,
      "configurability": 0,
      "cost": 0,
      "deployability": 0,
      "domain": 0,
      "elasticity": 0,
      "evolvability": 0,
      "fault-tolerance": 0,
      "interoperability": 0,
      "performance": 0,
      "scalability": 0,
      "simplicity": 0,
      "testability": 0,
      "workflow": 0,
    },
    "microkernel": {
      "agility": 0,
      "abstraction": 0,
      "configurability": 0,
      "cost": 0,
      "deployability": 0,
      "domain": 0,
      "elasticity": 0,
      "evolvability": 0,
      "fault-tolerance": 0,
      "interoperability": 0,
      "performance": 0,
      "scalability": 0,
      "simplicity": 0,
      "testability": 0,
      "workflow": 0,
    },
    "microservices": {
      "agility": 0,
      "abstraction": 0,
      "configurability": 0,
      "cost": 0,
      "deployability": 0,
      "domain": 0,
      "elasticity": 0,
      "evolvability": 0,
      "fault-tolerance": 0,
      "interoperability": 0,
      "performance": 0,
      "scalability": 0,
      "simplicity": 0,
      "testability": 0,
      "workflow": 0,
    },
    "service-based": {
      "agility": 0,
      "abstraction": 0,
      "configurability": 0,
      "cost": 0,
      "deployability": 0,
      "domain": 0,
      "elasticity": 0,
      "evolvability": 0,
      "fault-tolerance": 0,
      "interoperability": 0,
      "performance": 0,
      "scalability": 0,
      "simplicity": 0,
      "testability": 0,
      "workflow": 0,
    },
    "service-oriented": {
      "agility": 0,
      "abstraction": 0,
      "configurability": 0,
      "cost": 0,
      "deployability": 0,
      "domain": 0,
      "elasticity": 0,
      "evolvability": 0,
      "fault-tolerance": 0,
      "interoperability": 0,
      "performance": 0,
      "scalability": 0,
      "simplicity": 0,
      "testability": 0,
      "workflow": 0,
    },
    "event-driven": {
      "agility": 0,
      "abstraction": 0,
      "configurability": 0,
      "cost": 0,
      "deployability": 0,
      "domain": 0,
      "elasticity": 0,
      "evolvability": 0,
      "fault-tolerance": 0,
      "interoperability": 0,
      "performance": 0,
      "scalability": 0,
      "simplicity": 0,
      "testability": 0,
      "workflow": 0,
    },
    "space-based": {
      "agility": 0,
      "abstraction": 0,
      "configurability": 0,
      "cost": 0,
      "deployability": 0,
      "domain": 0,
      "elasticity": 0,
      "evolvability": 0,
      "fault-tolerance": 0,
      "interoperability": 0,
      "performance": 0,
      "scalability": 0,
      "simplicity": 0,
      "testability": 0,
      "workflow": 0,
    },
  };

  Map<String, Map<String, int>> get architectures => _architectures;
}
