class ArchitecturesModel {
  final _architectures = {
    "layered": {
      "agility": 1,
      "abstraction": 1,
      "configurability": 1,
      "cost": 5,
      "deployability": 1,
      "domain": 1,
      "elasticity": 1,
      "evolvability": 1,
      "fault-tolerance": 1,
      "integration": 1,
      "interoperability": 1,
      "performance": 3,
      "scalability": 1,
      "simplicity": 5,
      "testability": 2,
      "workflow": 1,
    },
    "modular monolith": {
      "agility": 2,
      "abstraction": 1,
      "configurability": 1,
      "cost": 5,
      "deployability": 2,
      "domain": 5,
      "elasticity": 1,
      "evolvability": 1,
      "fault-tolerance": 1,
      "integration": 1,
      "interoperability": 1,
      "performance": 3,
      "scalability": 1,
      "simplicity": 5,
      "testability": 2,
      "workflow": 1,
    },
    "microkernel": {
      "agility": 3,
      "abstraction": 3,
      "configurability": 4,
      "cost": 5,
      "deployability": 3,
      "domain": 5,
      "elasticity": 1,
      "evolvability": 3,
      "fault-tolerance": 1,
      "integration": 3,
      "interoperability": 3,
      "performance": 3,
      "scalability": 1,
      "simplicity": 4,
      "testability": 3,
      "workflow": 2,
    },
    "microservices": {
      "agility": 5,
      "abstraction": 1,
      "configurability": 3,
      "cost": 1,
      "deployability": 5,
      "domain": 5,
      "elasticity": 5,
      "evolvability": 5,
      "fault-tolerance": 5,
      "integration": 3,
      "interoperability": 3,
      "performance": 2,
      "scalability": 5,
      "simplicity": 1,
      "testability": 5,
      "workflow": 1,
    },
    "service-based": {
      "agility": 4,
      "abstraction": 1,
      "configurability": 2,
      "cost": 4,
      "deployability": 4,
      "domain": 5,
      "elasticity": 2,
      "evolvability": 3,
      "fault-tolerance": 4,
      "integration": 2,
      "interoperability": 2,
      "performance": 3,
      "scalability": 3,
      "simplicity": 3,
      "testability": 4,
      "workflow": 1,
    },
    "service-oriented": {
      "agility": 1,
      "abstraction": 5,
      "configurability": 1,
      "cost": 1,
      "deployability": 1,
      "domain": 1,
      "elasticity": 2,
      "evolvability": 1,
      "fault-tolerance": 3,
      "integration": 5,
      "interoperability": 5,
      "performance": 2,
      "scalability": 3,
      "simplicity": 1,
      "testability": 1,
      "workflow": 5,
    },
    "event-driven": {
      "agility": 3,
      "abstraction": 4,
      "configurability": 2,
      "cost": 3,
      "deployability": 3,
      "domain": 1,
      "elasticity": 4,
      "evolvability": 5,
      "fault-tolerance": 5,
      "integration": 3,
      "interoperability": 3,
      "performance": 5,
      "scalability": 5,
      "simplicity": 1,
      "testability": 2,
      "workflow": 5,
    },
    "space-based": {
      "agility": 2,
      "abstraction": 1,
      "configurability": 2,
      "cost": 2,
      "deployability": 3,
      "domain": 5,
      "elasticity": 5,
      "evolvability": 3,
      "fault-tolerance": 3,
      "integration": 2,
      "interoperability": 2,
      "performance": 5,
      "scalability": 5,
      "simplicity": 1,
      "testability": 1,
      "workflow": 1,
    },
  };

  Map<String, Map<String, int>> get architectures => _architectures;
}
